services:
  application:
    build: .
    image: quizlecik/projekt:1.0
    container_name: projekt
    ports:
      - "8080:8080"
    environment:
      - "SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/projekt"
      - "SPRING_DATA_MONGODB_URI=mongodb://root:admin@mongo:27017/projekt"
      - "MONGO_URI=mongodb://root:admin@mongo:27017"
      - "LOG_FILE_PATH=/logs/app.json"
    volumes:
      - ./logs:/logs
    depends_on:
      mysql:
        condition: service_healthy
      mongo:
        condition: service_healthy
    restart: always