services:
  adminer:
    image: adminer:4.8.1
    container_name: adminer
    ports:
      - "8090:8080"
    depends_on:
      mysql:
        condition: service_healthy
    profiles:
      - dev

  mysql:
    image: mysql:8.4.0
    container_name: mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=admin"
      - "MYSQL_DATABASE=projekt"
    ports:
      - "3306:3306"
    volumes:
      - mysqldb:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent", "--protocol", "tcp" ]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    restart: always

volumes:
  mysqldb: