spring:
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  liquibase:
    contexts: test
    change-log: classpath:db/changelog/master-test.xml
  web:
    resources:
      static-locations: classpath:/static/,file:uploads/
  app:
    storage:
      location: uploads


deepl:
  auth-key: 8ec376ab-7847-48d6-9941-23856ca6a578:fx
logging:
  level:
    org.mongodb.driver: WARN
