spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quizlecik
    username: root
    password:
  liquibase:
    contexts: prod
  web:
    resources:
      static-locations: classpath:/static/,file:C:\Users\Szymon\uploads
app:
  storage:
    location: C:\Users\Szymon\uploads