spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url:  jdbc:mysql://mysql:3306/projekt
    username: root
    password: admin
  sql:
    init:
      mode: always


  liquibase:
    change-log: classpath:db/changelog/master.xml
  data:
    mongodb:
      uri: mongodb://root:admin@mongo:27017/projekt?maxPoolSize=50&minPoolSize=10&maxIdleTimeMS=30000&waitQueueTimeoutMS=5000
  web:
    resources:
      static-locations: classpath:/static/,file:uploads/







deepl:
    auth-key: 8ec376ab-7847-48d6-9941-23856ca6a578:fx
logging:
  level:
    org.mongodb.driver: WARN