spring:
  datasource:
    url: jdbc:h2:mem:test
  liquibase:
    contexts: dev
    change-log: classpath:db/changelog/master.xml
  web:
    resources:
      static-locations: classpath:/static/,file:uploads/
app:
  storage:
    location: uploads
deepl:
  auth-key: 8ec376ab-7847-48d6-9941-23856ca6a578:fx
