spring:
  jpa:
    hibernate:
      ddl-auto: validate
  sql:
    init:
      mode: always

  web:
    resources:
      static-locations: classpath:/static/,file:uploads/
deepl:
  auth-key: ${DEEPL_AUTH_KEY}
logging:
  level:
    org.mongodb.driver: WARN