spring:
  jpa:
    hibernate:
      ddl-auto: validate
  sql:
    init:
      mode: always
  liquibase:
    change-log: classpath:db/changelog/master.xml
  docker:
    compose:
      file: compose-database.yml
      stop:
        command: down
      profiles:
        active: dev