spring:
  datasource:
    url: jdbc:mysql://mysql:3306/projekt
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  sql:
    init:
      mode: always

  web:
    resources:
      static-locations: classpath:/static/,file:uploads/
deepl:
  auth-key: 8ec376ab-7847-48d6-9941-23856ca6a578:fx
logging:
  level:
    org.mongodb.driver: WARN
  h2:
    console:
      enabled: true
      path: /h2-console