spring:
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  liquibase:
    contexts: test
    change-log: classpath:db/changelog/master-test.xml
  web:
    resources:
      static-locations: classpath:/static/,file:uploads/
  app:
    storage:
      location: uploads

logging:
  level:
    org.mongodb.driver: WARN
